name: Prod

description: Assemble release

runs:
  using: "composite"
  steps:
    # Checkout code ------------------------------------------------------------
    - name: Check out code
      uses: actions/checkout@v4

    # Setup Nodejs versions ----------------------------------------------------
    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    # Print version names ------------------------------------------------------
    - name: Output Node version
      shell: bash
      run: node --version
    - name: Output Yarn version
      shell: bash
      run: yarn --version

    # Get and install all deps -------------------------------------------------
    - name: Install Dependencies
      shell: bash
      run: yarn install --frozen-lockfile

    # Build application --------------------------------------------------------
    - name: Setup web client
      shell: bash
      run: yarn build
